/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<'github' | 'moon-1' | 'moon' | 'sun-1' | 'sun'>;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<'github' | 'moon-1' | 'moon' | 'sun-1' | 'sun'>;
          default: string;
          required: true;
      };
  }>>, {
      name: 'github' | 'moon-1' | 'moon' | 'sun-1' | 'sun';
  }>;
  export const svgNames: ['github','moon-1','moon','sun-1','sun'];
  export type SvgName = 'github' | 'moon-1' | 'moon' | 'sun-1' | 'sun';
  export default SvgIcon;
}
