/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
export type SvgName = 'github' | 'moon-1' | 'moon' | 'sun-1' | 'sun'
