import { readdir, readFile, writeFile } from 'fs/promises'
import { resolve } from 'path'
import { xml2json, js2xml } from 'xml-js'

interface AST {
  type?: string
  name?: string
  attributes?: {
    width: string
    height: string
    viewBox: string
    fill: string
    xmlns: string
    stroke?: string
  }
  elements?: Array<AST>
}

const traversePathFill = (node: AST) => {
  if (!node) return

  if (node.name === 'path') {
    if (node.attributes?.fill) {
      node.attributes.fill = 'currentColor'
    }

    if (node.attributes?.stroke) {
      node.attributes.stroke = 'currentColor'
    }
  }

  if (Array.isArray(node.elements)) {
    node.elements = node.elements.filter((target) => {
      return target.name !== 'title'
    })

    node.elements.forEach((target) => {
      traversePathFill(target)
    })
  }
}
export function formatSvg(node: string) {
  const parseAst = JSON.parse(xml2json(node, { spaces: 4 })) as AST

  traversePathFill(parseAst)

  return js2xml(parseAst, { spaces: 4 })
}

async function bootstrap() {
  const files = await readdir(resolve(process.cwd(), './src/assets/svgs'), {
    withFileTypes: true,
    recursive: true,
  })

  let filesNames: string[] = []
  files.forEach(async (target) => {
    if (target.isFile()) {
      filesNames.push(target.name)
      if (target.name.endsWith('.fill.svg')) {
        return
      }

      const internalPath = resolve(target.parentPath, target.name)
      const svgStr = await readFile(internalPath, 'utf-8')
      const res = formatSvg(svgStr)
      if (res) {
        writeFile(internalPath, res, 'utf-8')
      }
    }
  })

  const iconNameList = filesNames
    .map((target) => target.replace(/\.svg$/, ''))
    .map((target) => `'${target}'`)

  const iconNameTypes = iconNameList.join(' | ')
  const iconNameDts = iconNameList.join(',')

  const svgGlobalComponentsDts = `
/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component

import "vue";
declare module "vue" {
	export interface GlobalComponents {
      SvgIcon: import('vue').DefineComponent<
        {
          name: {
            type: import('vue').PropType<
            ${iconNameTypes}>
            default: string
            required: true
          }
        },
        {},
        unknown,
        {},
        {},
        import('vue').ComponentOptionsMixin,
        import('vue').ComponentOptionsMixin,
        {},
        string,
        import('vue').VNodeProps &
          import('vue').AllowedComponentProps &
          import('vue').ComponentCustomProps,
        Readonly<
          import('vue').ExtractPropTypes<{
            name: {
              type: import('vue').PropType<
               ${iconNameTypes}
              >
              default: string
              required: true
            }
          }>
        >,
        {
          name: ${iconNameTypes}

        }
	    >
  }
}
  `

  writeFile(
    resolve(process.cwd(), './src/types/svg-component-global.d.ts'),
    svgGlobalComponentsDts,
    'utf-8',
  )

  const svgComponentDts = `

/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<${iconNameTypes}>;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<${iconNameTypes}>;
          default: string;
          required: true;
      };
  }>>, {
      name: ${iconNameTypes};
  }>;
  export const svgNames: [${iconNameDts}];
  export type SvgName = ${iconNameTypes};
  export default SvgIcon;
}
`
  writeFile(
    resolve(process.cwd(), './src/types/svg-component.d.ts'),
    svgComponentDts,
    'utf-8',
  )
}

bootstrap()
